// Official product images, saved in public/images and credited in CREDITS.md.
// "frame" is the color shown behind an image whose shape does not match the
// card, so the whole image is visible instead of being cropped.
export const products = [
  {
    id: "khanmigo",
    name: "Khanmigo",
    maker: "Khan Academy",
    type: "Chatbot tutor",
    url: "https://www.khanmigo.ai/",
    image: "/images/khanmigo.png",
    frame: "#eee5fb",
    text: "Launched in March 2023 on GPT-4. The student types a question and Khanmigo guides them through the problem in plain language, in a conversation window, instead of handing over the answer.",
  },
  {
    id: "notebooklm",
    name: "Gemini Notebook",
    maker: "Google, renamed from NotebookLM in 2026",
    type: "Source-grounded study assistant",
    url: "https://notebooklm.google/",
    image: "/images/notebooklm.png",
    frame: "#ffffff",
    text: "The student uploads their own notes, readings, or lecture slides, and the assistant answers only from that material. This keeps the tutor tied to what the class actually covered.",
  },
  {
    id: "claude",
    name: "Claude for Education",
    maker: "Anthropic",
    type: "Guided study mode",
    url: "https://www.anthropic.com/education",
    image: "/images/claude-education.jpg",
    frame: "#d97757",
    text: "Part of the guardrail era that began in 2025. A learning mode that asks the student questions and gives hints rather than direct answers, the approach the PNAS study found avoids harm.",
  },
  {
    id: "chatgpt",
    name: "ChatGPT study mode",
    maker: "OpenAI",
    type: "Guided study mode",
    url: "https://openai.com/index/chatgpt-study-mode/",
    image: "/images/chatgpt-study.png",
    frame: "#5ec8f5",
    text: "A dedicated study mode inside the general chatbot most students already use. It works through a problem step by step instead of giving the answer straight away.",
  },
  {
    id: "duolingo",
    name: "Duolingo Max",
    maker: "Duolingo",
    type: "Adaptive practice platform",
    url: "https://blog.duolingo.com/duolingo-max/",
    image: "/images/duolingo-max.png",
    frame: "#000000",
    text: "Duolingo launched in 2012 and brought machine learning to a mass-market learning app. Lessons track what the learner gets right and wrong, then choose the next exercise to fit. Max added generative AI features in 2023.",
  },
  {
    id: "turbo",
    name: "Turbo AI",
    maker: "TurboLearn",
    type: "Wrapper study app",
    url: "https://www.turbolearn.ai/",
    image: "/images/turbolearn.png",
    frame: "#0e0a1f",
    text: "A study interface built on top of another company's AI model. Wrapper apps like this charge 9.99 to 19.99 dollars a month for a thin layer over a model they did not build.",
  },
];
